version: 0.2

phases:
  install:
    commands:
      - echo "Installing prerequisites (if any)..."

  build:
    commands:
      - echo "Listing repo files:"
      - ls -R
      - echo "Copying files to S3 bucket..."
      - aws s3 cp . s3://dag-pipeline-storage/script/ --recursive

artifacts:
  files:
    - '**/*'
